=== arm32x/funkin-modish/assets/preload/data/characters/character-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "FNF Modish Character",
    "description": "A character definition file for the Friday Night Funkin' mod loader Modish.",
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "enum": [ "sparrow", "packer" ]
        },
        "atlas": {
            "type": "string"
        },
        "animations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "prefix": {
                        "type": "string"
                    },
                    "indices": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    },
                    "postfix": {
                        "type": "string"
                    },
                    "frameRate": {
                        "type": "integer"
                    },
                    "looped": {
                        "type": "boolean"
                    },
                    "condition": {
                        "type": "string",
                        "enum": [ "player", "not-player" ]
                    },
                    "offsets": {
                        "type": "array",
                        "minItems": 2,
                        "maxItems": 2,
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "required": [ "name", "prefix", "offsets" ],
                "dependencies": {
                    "postfix": [ "indices" ]
                }
            }
        },
        "startingAnimation": {
            "description": "The animation to play after initialization.",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "force": {
                    "type": "boolean"
                },
                "reversed": {
                    "type": "boolean"
                },
                "frame": {
                    "type": "integer"
                },
                "playOnly": {
                    "type": "boolean"
                }
            },
            "required": [ "name" ]
        },
        "antialiasing": {
            "type": "boolean"
        },
        "flipX": {
            "type": "boolean"
        },
        "flipY": {
            "type": "boolean"
        },
        "pixel": {
            "$comment": "TODO: Replace this with something more extensible.",
            "description": "Scales the sprite up 6x.",
            "type": "boolean"
        }
    },
    "required": [ "type", "atlas" ]
}

=== arm32x/funkin-modish/assets/preload/data/characters/bf-car.json
{
    "$schema": "./character-schema.json",
    "type": "sparrow",
    "atlas": "bfCar",
    "animations": [
        {
            "name": "idle",
            "prefix": "BF idle dance",
            "frameRate": 24,
            "looped": false,
            "offsets": [-5, 0]
        },
        {
            "name": "singUP",
            "prefix": "BF NOTE UP0",
            "frameRate": 24,
            "looped": false,
            "offsets": [-29, 27]
        },
        {
            "name": "singLEFT",
            "prefix": "BF NOTE LEFT0",
            "frameRate": 24,
            "looped": false,
            "offsets": [12, -6]
        },
        {
            "name": "singRIGHT",
            "prefix": "BF NOTE RIGHT0",
            "frameRate": 24,
            "looped": false,
            "offsets": [-38, -7]
        },
        {
            "name": "singDOWN",
            "prefix": "BF NOTE DOWN0",
            "frameRate": 24,
            "looped": false,
            "offsets": [-10, -50]
        },
        {
            "name": "singUPmiss",
            "prefix": "BF NOTE UP MISS",
            "frameRate": 24,
            "looped": false,
            "offsets": [-29, 27]
        },
        {
            "name": "singLEFTmiss",
            "prefix": "BF NOTE LEFT MISS",
            "frameRate": 24,
            "looped": false,
            "offsets": [12, 24]
        },
        {
            "name": "singRIGHTmiss",
            "prefix": "BF NOTE RIGHT MISS",
            "frameRate": 24,
            "looped": false,
            "offsets": [-30, 21]
        },
        {
            "name": "singDOWNmiss",
            "prefix": "BF NOTE DOWN MISS",
            "frameRate": 24,
            "looped": false,
            "offsets": [-11, -19]
        },
        {
            "name": "hey",
            "prefix": "BF HEY",
            "frameRate": 24,
            "looped": false,
            "offsets": [7, 4]
        }
    ],
    "startingAnimation": {
        "name": "idle"
    },
    "flipX": true
}

=== arm32x/funkin-modish/assets/preload/data/characters/mom.json
{
    "$schema": "./character-schema.json",
    "type": "sparrow",
    "atlas": "Mom_Assets",
    "animations": [
        {
            "name": "idle",
            "prefix": "Mom Idle",
            "frameRate": 24,
            "looped": false,
            "offsets": [0, 0]
        },
        {
            "name": "singUP",
            "prefix": "Mom Up Pose",
            "frameRate": 24,
            "looped": false,
            "offsets": [14, 71]
        },
        {
            "name": "singDOWN",
            "prefix": "MOM DOWN POSE",
            "frameRate": 24,
            "looped": false,
            "offsets": [20, -160]
        },
        {
            "name": "singLEFT",
            "prefix": "Mom Left Pose",
            "frameRate": 24,
            "looped": false,
            "offsets": [250, -23]
        },
        {
            "$comment": "ANIMATION IS CALLED MOM LEFT POSE BUT ITS FOR THE RIGHT CUZ DAVE IS DUMB!",
            "name": "singRIGHT",
            "prefix": "Mom Pose Left",
            "frameRate": 24,
            "looped": false,
            "offsets": [10, -60]
        }
    ],
    "startingAnimation": {
        "name": "idle"
    }
}

=== arm32x/funkin-modish/assets/preload/data/characters/parents-christmas.json
{
    "$schema": "./character-schema.json",
    "type": "sparrow",
    "atlas": "mom_dad_christmas_assets",
    "animations": [
        {
            "name": "idle",
            "prefix": "Parent Christmas Idle",
            "frameRate": 24,
            "looped": false,
            "offsets": [0, 0]
        },
        {
            "name": "singUP",
            "prefix": "Parent Up Note Dad",
            "frameRate": 24,
            "looped": false,
            "offsets": [-47, 24]
        },
        {
            "name": "singDOWN",
            "prefix": "Parent Down Note Dad",
            "frameRate": 24,
            "looped": false,
            "offsets": [-31, -29]
        },
        {
            "name": "singLEFT",
            "prefix": "Parent Left Note Dad",
            "frameRate": 24,
            "looped": false,
            "offsets": [-30, 16]
        },
        {
            "name": "singRIGHT",
            "prefix": "Parent Right Note Dad",
            "frameRate": 24,
            "looped": false,
            "offsets": [-1, -23]
        },
        {
            "name": "singUP-alt",
            "prefix": "Parent Up Note Mom",
            "frameRate": 24,
            "looped": false,
            "offsets": [-47, 24]
        },
        {
            "name": "singDOWN-alt",
            "prefix": "Parent Down Note Mom",
            "frameRate": 24,
            "looped": false,
            "offsets": [-30, -27]
        },
        {
            "name": "singLEFT-alt",
            "prefix": "Parent Left Note Mom",
            "frameRate": 24,
            "looped": false,
            "offsets": [-30, 15]
        },
        {
            "name": "singRIGHT-alt",
            "prefix": "Parent Right Note Mom",
            "frameRate": 24,
            "looped": false,
            "offsets": [-1, -24]
        }
    ],
    "startingAnimation": {
        "name": "idle"
    }
}
